- name: checking id
  command: id
  become: false   # disable become so we can get id of the remote user vs id of root
  register: check_id_result
  changed_when: false

- name: update sshd config
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart sshd
  # only run this when sshusers group exists and current user is member
  when: ('stdout' in check_id_result) and (check_id_result.stdout.find('(sshusers)') != -1)

- name: checking for rack user
  command: id rack
  register: rack_user_result
  changed_when: false
  failed_when: false

- name: add rack user to sshusers
  user:
    name: rack
    groups: sshusers
    append: yes
  # only run when rack user exists
  when: ('stdout' in rack_user_result) and (rack_user_result.stdout.find('(rack)') != -1)
